In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

EV_consumption_path = "my_data/EV_consumption_data.csv"
EV_consumption = pd.read_csv(EV_consumption_path)

Tradition_consumption_path = "my_data/Tradition_consumption_data.csv"
Tradition_consumption = pd.read_csv(Tradition_consumption_path,encoding='ISO-8859-1')

In [2]:
EV_consumption.head()

,Model Year,Mfr Name,Division,Carline,FE Rating (1-10 rating on Label),Fuel Unit - Conventional Fuel,Fuel Usage Desc - Conventional Fuel,Range1 - Model Type Driving Range - Conventional Fuel,City FE (Guide) - Conventional Fuel,Hwy FE (Guide) - Conventional Fuel,Comb FE (Guide) - Conventional Fuel,City Unadj FE - Conventional Fuel,Hwy Unadj FE - Conventional Fuel,Comb Unadj FE - Conventional Fuel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023 Audi e-tron GT,NaN,NaN
2,2023.0,Volkswagen Group of,Audi,e-tron GT,10.0,MPG,Electricity,238.0,81.0,83.0,82.0,113.2,116.3000,114.5743
3,2023.0,Volkswagen Group of,Audi,e-tron GT,10.0,KW-HR/100Miles,Electricity,238.0,42.0,41.0,41.0,29.7878,28.9764,29.4227
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023 Audi RS e-tron GT,NaN,NaN

In [3]:
#clean EV_consumption
EV_consumption = EV_consumption.copy()
EV_consumption = EV_consumption.dropna(subset=['Model Year'])
EV_consumption.insert(0, 'Models', '')
EV_consumption['Models'] = EV_consumption['Model Year'].astype(str) + '_' + EV_consumption['Mfr Name'] + '_' + EV_consumption['Division'] + '_' + EV_consumption['Carline']
EV_consumption = EV_consumption[EV_consumption['Fuel Unit - Conventional Fuel'] != 'KW-HR/100Miles']
EV_consumption.drop(columns=['Model Year','Mfr Name','Division','Carline','FE Rating (1-10 rating on Label)',"Range1 - Model Type Driving Range - Conventional Fuel","City Unadj FE - Conventional Fuel","Hwy Unadj FE - Conventional Fuel","Comb Unadj FE - Conventional Fuel"], inplace=True)
EV_consumption.head()
EV_consumption_cleaned = EV_consumption

In [170]:
#EV_consumption_cleaned.to_csv("my_data/cleaned_data/EV_consumption_cleaned.csv", index=False)

In [4]:
EV_consumption_cleaned.head()

,Models,Fuel Unit - Conventional Fuel,Fuel Usage Desc - Conventional Fuel,City FE (Guide) - Conventional Fuel,Hwy FE (Guide) - Conventional Fuel,Comb FE (Guide) - Conventional Fuel
2,2023.0_Volkswagen Group of_Audi_e-tron GT,MPG,Electricity,81.0,83.0,82.0
5,2023.0_Volkswagen Group of_Audi_RS e-tron GT,MPG,Electricity,79.0,82.0,81.0
8,2023.0_Volkswagen Group of_Audi_Q4 e-tron,MPG,Electricity,112.0,94.0,103.0
11,2023.0_Volkswagen Group of_Audi_e-tron quattro,MPG,Electricity,78.0,79.0,79.0
14,2023.0_Volkswagen Group of_Audi_e-tron S (20in...,MPG,Electricity,72.0,75.0,73.0

In [5]:
#Clean Tradition_consumption
Tradition_consumption = Tradition_consumption.copy()
Tradition_consumption.insert(0, 'Models', '')
Tradition_consumption['Models'] = Tradition_consumption['Model Year'].astype(str) + '_' + Tradition_consumption['Division'] + '_' + Tradition_consumption['Carline'] 
Tradition_consumption.drop(columns=['Model Year','Division','Carline',"City Unadj FE - Conventional Fuel","Hwy Unadj FE - Conventional Fuel","Comb Unadj FE - Conventional Fuel"], inplace=True)
Tradition_consumption.head()

,Models,Fuel Usage Desc - Conventional Fuel,Fuel Unit - Conventional Fuel,Fuel Unit Desc - Conventional Fuel,City FE (Guide) - Conventional Fuel,Hwy FE (Guide) - Conventional Fuel,Comb FE (Guide) - Conventional Fuel
0,2023_Aston Martin Lagonda Ltd_V12 Vantage,Gasoline (Premium Unleaded Recommended),MPG,miles per gallon,14,22,16
1,2023_Aston Martin Lagonda Ltd_Vantage V8,Gasoline (Premium Unleaded Recommended),MPG,miles per gallon,18,24,20
2,2023_Audi_R8 Coupe quattro,Gasoline (Premium Unleaded Required),MPG,miles per gallon,13,18,15
3,2023_Audi_R8 Coupe RWD,Gasoline (Premium Unleaded Required),MPG,miles per gallon,14,23,17
4,2023_Audi_R8 GT RWD,Gasoline (Premium Unleaded Required),MPG,miles per gallon,14,21,17

In [6]:
Tradition_consumption_cleaned = Tradition_consumption

In [ ]:
Tradition_consumption_cleaned.to_csv("my_data/cleaned_data/Tradition_consumption_cleaned.csv", index=False)

In [7]:
EV_consumption_cleaned = EV_consumption_cleaned.rename(columns={
    'Fuel Unit - Conventional Fuel': 'Fuel_unit',
    'Fuel Usage Desc - Conventional Fuel': 'Fuel_usage',
    'City FE (Guide) - Conventional Fuel': 'City_FE',
    'Hwy FE (Guide) - Conventional Fuel': 'Hwy_FE',
    'Comb FE (Guide) - Conventional Fuel': 'Comb_FE'
})
cols = EV_consumption_cleaned.columns.tolist()
cols = cols[:1] + [cols[2]] + [cols[1]] + cols[3:]
EV_consumption_cleaned = EV_consumption_cleaned[cols]



EV_consumption_cleaned.head()

,Models,Fuel_usage,Fuel_unit,City_FE,Hwy_FE,Comb_FE
2,2023.0_Volkswagen Group of_Audi_e-tron GT,Electricity,MPG,81.0,83.0,82.0
5,2023.0_Volkswagen Group of_Audi_RS e-tron GT,Electricity,MPG,79.0,82.0,81.0
8,2023.0_Volkswagen Group of_Audi_Q4 e-tron,Electricity,MPG,112.0,94.0,103.0
11,2023.0_Volkswagen Group of_Audi_e-tron quattro,Electricity,MPG,78.0,79.0,79.0
14,2023.0_Volkswagen Group of_Audi_e-tron S (20in...,Electricity,MPG,72.0,75.0,73.0

In [8]:
Tradition_consumption_cleaned = Tradition_consumption_cleaned.rename(columns={
    'Fuel Unit - Conventional Fuel': 'Fuel_unit',
    'Fuel Usage Desc - Conventional Fuel': 'Fuel_usage',
    'City FE (Guide) - Conventional Fuel': 'City_FE',
    'Hwy FE (Guide) - Conventional Fuel': 'Hwy_FE',
    'Comb FE (Guide) - Conventional Fuel': 'Comb_FE'
})
Tradition_consumption_cleaned = Tradition_consumption_cleaned.drop(['Fuel Unit Desc - Conventional Fuel'], axis=1)
Tradition_consumption_cleaned[['City_FE', 'Hwy_FE', 'Comb_FE']] = Tradition_consumption_cleaned[['City_FE', 'Hwy_FE', 'Comb_FE']].astype(float)



Tradition_consumption_cleaned.head()

,Models,Fuel_usage,Fuel_unit,City_FE,Hwy_FE,Comb_FE
0,2023_Aston Martin Lagonda Ltd_V12 Vantage,Gasoline (Premium Unleaded Recommended),MPG,14.0,22.0,16.0
1,2023_Aston Martin Lagonda Ltd_Vantage V8,Gasoline (Premium Unleaded Recommended),MPG,18.0,24.0,20.0
2,2023_Audi_R8 Coupe quattro,Gasoline (Premium Unleaded Required),MPG,13.0,18.0,15.0
3,2023_Audi_R8 Coupe RWD,Gasoline (Premium Unleaded Required),MPG,14.0,23.0,17.0
4,2023_Audi_R8 GT RWD,Gasoline (Premium Unleaded Required),MPG,14.0,21.0,17.0

In [9]:
#Merge
merged_consumption_df = pd.concat([EV_consumption_cleaned, Tradition_consumption_cleaned], axis=0, ignore_index=True)

merged_consumption_df.head()

,Models,Fuel_usage,Fuel_unit,City_FE,Hwy_FE,Comb_FE
0,2023.0_Volkswagen Group of_Audi_e-tron GT,Electricity,MPG,81.0,83.0,82.0
1,2023.0_Volkswagen Group of_Audi_RS e-tron GT,Electricity,MPG,79.0,82.0,81.0
2,2023.0_Volkswagen Group of_Audi_Q4 e-tron,Electricity,MPG,112.0,94.0,103.0
3,2023.0_Volkswagen Group of_Audi_e-tron quattro,Electricity,MPG,78.0,79.0,79.0
4,2023.0_Volkswagen Group of_Audi_e-tron S (20in...,Electricity,MPG,72.0,75.0,73.0

In [10]:
merged_consumption_df['Fuel_usage'] = merged_consumption_df['Fuel_usage'].apply(lambda x: 'Gasoline' if x != 'Electricity' else x)
merged_consumption_df.head()

,Models,Fuel_usage,Fuel_unit,City_FE,Hwy_FE,Comb_FE
0,2023.0_Volkswagen Group of_Audi_e-tron GT,Electricity,MPG,81.0,83.0,82.0
1,2023.0_Volkswagen Group of_Audi_RS e-tron GT,Electricity,MPG,79.0,82.0,81.0
2,2023.0_Volkswagen Group of_Audi_Q4 e-tron,Electricity,MPG,112.0,94.0,103.0
3,2023.0_Volkswagen Group of_Audi_e-tron quattro,Electricity,MPG,78.0,79.0,79.0
4,2023.0_Volkswagen Group of_Audi_e-tron S (20in...,Electricity,MPG,72.0,75.0,73.0

In [12]:
merged_consumption_df.to_csv("my_data/cleaned_data/merged_consumption.csv", index=False)